### ISSUE TITLE
#TK03 Menú

### ISSUE THREAD

**Issue by emigillini** [ISPC-23/Fullstack_Mobil_2024#3]
Editar cada clase para que contenga los métodos que dotan de funcionalidad a los menú en cada activity:

- onCreateOptionsMenu
- onOptionsItemSelected
- onPrepareOptionsMenu

Historia de usuario #US09

**Comment by Verosolc30** [comment]
Creo menù

**Comment by fedekrenn** [comment]
Se verifica aplicado en las activities
