### ISSUE TITLE
#BUG05 - Login fallido

### ISSUE THREAD

**Issue by Ferbarletta** [ISPC-23/Fullstack_Mobil_2024#56]
Se detecta que, tras el login con credenciales válidas, la aplicación muestra el saludo de bienvenida al usuario pero no se redirige al productFragment.

https://github.com/user-attachments/assets/cfffd012-8d64-4499-b818-f2271a9e555c

**Comment by emigillini** [comment]
Problema resuelto: al ingresar correctamente las credenciales redirige al usuario a la vista de productos
