### ISSUE TITLE
#TF001 - Verificar que el usuario acceda a la aplicación correctamente

### ISSUE THREAD

**Issue by fedekrenn** [ISPC-23/Fullstack_Mobil_2024#64]
En el caso que el Usuario ingrese correctamente sus credenciales,
cuando oprima el botón "Iniciar sesión",
a continuación la aplicación valida su autenticidad y es direccionado a la pantalla de "Productos".
Precondiciones: La cuenta del usuario debe existir y estar activa.
Datos de Prueba: Correo: [admin@admin.com](mailto:admin@admin.com) Contraseña: admin
Pasos: 
1. Abrir la app. 
2. Ingresar el correo electrónico en el campo correspondiente 
3. Ingresar contraseña en el campo correspondiente 
4. Oprimir el botón "Iniciar sesión"
Resultado Esperado: El sistema verifica las credenciales y redirige al catálogo de productos si son correctas.
Pass/Fail: FAIL
Prioridad: Crítica
#Etiquetas: #Prueba de Funcionalidad #Prueba de Integración #caja negra

Fecha de ejecución: 14/10/2024
Comentarios: Se genera el #BUG05 - Login fallido (#56) en el tablero Kanba: Luego de ingresar credenciales válidas, se oprime el botón "Iniciar sesión" y la aplicación se cierra.

**Comment by g3rm6n** [comment]
Diseñado por: Fernando Barletta
Ejecutado por: Fernando Barletta
