### ISSUE TITLE
#TK04 Vista de detalle de producto 

### ISSUE THREAD

**Issue by FernandaACastillo** [ISPC-23/Fullstack_Mobil_2024#7]
Añadir la activity y clase correspondiente para la pantalla de detalle de producto

Historia de usuario #US02

**Comment by fedekrenn** [comment]
Se crea la activity y clase, se comienza con el diseño

**Comment by fedekrenn** [comment]
#47 Se presenta el bug, por lo que se trabaja para su solución

**Comment by fedekrenn** [comment]
Se corrige ok bug
